apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: camunda-zeebe-config-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 100Mi
  volumeName: config-pv