apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: camunda-zebee-config-pvc
spec:
  storageClassName: #{STORAGE_CLASS}#
  accessModes:
    - #{STORAGE_ACCESS_MODE}#
  resources:
    requests:
      storage: #{STORAGE_SIZE}#