apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-camunda-zeebe-pod
  labels:
    app: elasticsearch-camunda-zeebe-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-camunda-zeebe-pod
  template:
    metadata:
      labels:
        app: elasticsearch-camunda-zeebe-pod
    spec:
      containers:
      - name: elasticsearch-camunda-zeebe-pod
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
        env:
          - name: discovery.type
            value: "single-node"
          - name: cluster.name
            value: "elasticsearch"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
        volumeMounts:
        - name: zeebe_elasticsearch_data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: zeebe_elasticsearch_data
        persistentVolumeClaim:
          claimName: elasticsearch-camunda-zeebe-pvc
