apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: camunda-zeebe-elasticsearch-claim
spec:
  storageClassName: #{STORAGE_CLASS}#
  accessModes:
    - #{STORAGE_ACCESS_MODE}#
  resources:
    requests:
      storage: #{STORAGE_SIZE}#