name: CI-traditional-camunda

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Replace tokens in yaml files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/traditional/*.yaml"]'
        env:
          STORAGE_ACCESS_MODE: ${{secrets.STORAGE_ACCESS_MODE}}
          STORAGE_CLASS: ${{secrets.STORAGE_CLASS}}
          STORAGE_SIZE: ${{secrets.STORAGE_SIZE}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DOMAIN: ${{secrets.DOMAIN}}
      
      - name: Install yamls
        run: |
          kubectl apply -f ./traditional/