name: CI-camunda-zeebe

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Replace tokens in yaml files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["**/*.yaml"]'
        env:
          STORAGE_ACCESS_MODE: ${{secrets.STORAGE_ACCESS_MODE}}
          STORAGE_CLASS: ${{secrets.STORAGE_CLASS}}
          STORAGE_SIZE: ${{secrets.STORAGE_SIZE}}
          DOMAIN: ${{secrets.DOMAIN}}

      - name: Copy config file into configuration folder
        run: |
          kubectl apply -f init/init-camunda-zebee.yaml
          POD="$(kubectl get pods | awk '{print $1}' | grep init-camunda-zebee)"
          kubectl cp ./zeebe-config.yaml $POD:/usr/local/zeebe/config/application.yaml
          kubectl delete -f init/init-camunda-zebee.yaml

      # - name: Install pvc's
      #   run: |
      #     kubectl apply -f pvc-camunda-zebee-elasticsearch.yaml
      #     kubectl apply -f pvc-camunda-zebee-elasticsearch.yaml


      